parameters:
#    bionic_university_user.example.class: VG\UserBundle\Example

services:
#    bionic_university_user.example:
#        class: %bionic_university_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
