security:
    encoders:
#        VG\UserBundle\Entity\User:
#                            algorithm: sha512
#                            encode-as-base64: true
#                            iterations: 10
        Symfony\Component\Security\Core\User\User: plaintext
        VG\UserBundle\Security\User\RedisUser: sha512

    role_hierarchy:
        ROLE_USER: IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory]
        user:
            entity:
                class: VG\UserBundle\Entity\User
                property: email
                manager_name: ~
        redis:
            id: redis_user_provider
        in_memory:
            memory:
                users:
                    test:
                        password: 123456
                        roles: 'ROLE_USER'
                    admin:
                        password: 123456
                        roles: 'ROLE_ADMIN'

    firewalls:
        main:
            pattern: /.*
            form_login:
               check_path: /login_check
               login_path: /login
               default_target_path: /
               csrf_provider: form.csrf_provider
            logout:
               path:   /logout
               target: /
            security: true
            anonymous: true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
                - { path: /admin, role: ROLE_ADMIN }
                - { path: /*/*/edit, role: ROLE_ADMIN }
                - { path: /*/new, role: ROLE_ADMIN }
                - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

